version: "3"

services:
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    ports:
      - "3000:3000"

  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
    links:
      - backend
    ports:
      - "80:80"
