version: "3"

services:
  backend:
    image: myevents.frontend:latest
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: myevents.backend:latest
    build:
      dockerfile: Dockerfile
      context: ./frontend
    links:
      - backend
    ports:
      - "80:80"
