version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    links:
      - backend
    ports:
      - "80:80"
